title: Graham Guthrie
email: your-email@example.com
description: >- 
domain: grahamguthrie99.github.io 
baseurl: ""
url: https://grahamguthrie99.github.io

google_analytics: G-CQFG5WD47V 

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

